
# symbol_mapping.py
"""
Este diccionario mapea los símbolos de criptomonedas de CoinMarketCap a los símbolos correspondientes en Kraken.
Si una criptomoneda no está disponible en Kraken, se indica con 'No disponible'.
"""
symbol_mapping = {
    'BTC': 'XBT',
    'ETH': 'ETH',
    'USDT': 'USDT',
    'BNB': 'No disponible',
    'XRP': 'XRP',
    'USDC': 'USDC',
    'SOL': 'SOL',
    'ADA': 'ADA',
    'DOGE': 'DOGE',
    'DOT': 'DOT',
    'MATIC': 'MATIC',
    'DAI': 'DAI',
    'SHIB': 'SHIB',
    'TRX': 'TRX',
    'AVAX': 'AVAX',
    'UNI': 'UNI',
    'WBTC': 'No disponible',
    'LEO': 'No disponible',
    'LTC': 'LTC',
    'ATOM': 'ATOM',
    'LINK': 'LINK',
    'ETC': 'ETC',
    'XLM': 'XLM',
    'FTT': 'No disponible',
    'BCH': 'BCH',
    'XMR': 'XMR',
    'OKB': 'No disponible',
    'CRO': 'CRO',
    'ALGO': 'ALGO',
    'VET': 'No disponible',
    'NEAR': 'NEAR',
    'QNT': 'QNT',
    'ICP': 'ICP',
    'FLOW': 'FLOW',
    'FIL': 'FIL',
    'APE': 'APE',
    'HBAR': 'No disponible',
    'EGLD': 'EGLD',
    'XTZ': 'XTZ',
    'MANA': 'MANA',
    'SAND': 'SAND',
    'AXS': 'AXS',
    'KCS': 'No disponible',
    'AAVE': 'AAVE',
    'THETA': 'No disponible',
    'EOS': 'EOS',
    'CHZ': 'CHZ',
    'TUSD': 'No disponible',
    'USDP': 'No disponible',
    'MKR': 'MKR',
    'HT': 'No disponible',
    'BSV': 'BSV',
    'ZEC': 'ZEC',
    'KLAY': 'No disponible',
    'MIOTA': 'No disponible',
    'FTM': 'FTM',
    'SNX': 'SNX',
    'NEO': 'NEO',
    'GRT': 'GRT',
    'PAXG': 'PAXG',
    'CRV': 'CRV',
    'ENJ': 'ENJ',
    'BAT': 'BAT',
    'KAVA': 'KAVA',
    'COMP': 'COMP',
    'DASH': 'DASH',
    'LRC': 'LRC',
    'XEC': 'No disponible',
    'STX': 'STX',
    'AR': 'No disponible',
    'ZIL': 'ZIL',
    'GMT': 'No disponible',
    '1INCH': '1INCH',
    'RNDR': 'No disponible',
    'CELO': 'CELO',
    'BAL': 'BAL',
    'MINA': 'No disponible',
    'OMG': 'OMG',
    'NANO': 'NANO',
    'ICX': 'ICX',
    'SC': 'SC',
    'ANKR': 'ANKR',
    'OCEAN': 'OCEAN',
    'REQ': 'REQ',
    'STORJ': 'STORJ',
    'ANT': 'ANT',
    'REP': 'REP',
    'SUSHI': 'SUSHI',
    'KSM': 'KSM',
    'GLM': 'No disponible',
    'WAVES': 'WAVES',
    'REN': 'REN',
    'BNT': 'BNT',
    'MLN': 'MLN',
    'DGB': 'DGB',
    'NMR': 'NMR',
    'OXT': 'OXT',
    'GNO': 'GNO',
    'MCO': 'No disponible',
    'LSK': 'LSK',
    'YFI': 'YFI',
    'AUDIO': 'AUDIO',
    'POLY': 'No disponible',
    'FIL': 'FIL',
    'SRM': 'No disponible',
    'SXP': 'No disponible',
    'LPT': 'No disponible',
    'ALPHA': 'No disponible',
    'LUNA': 'No disponible',
    'UST': 'No disponible',
    'CVC': 'CVC',
    'DENT': 'No disponible',
    'QTUM': 'QTUM',
    'KNC': 'KNC',
    'BAND': 'BAND',
    'FET': 'FET',
    'ZEN': 'ZEN',
    'CHR': 'No disponible',
    'CHR': 'No disponible',
    'MANA': 'MANA',
    'GAL': 'No disponible',
    'PERP': 'No disponible',
    'SNT': 'SNT',
    'KEEP': 'KEEP',
    'REEF': 'No disponible',
    'REN': 'REN',
    'DIA': 'No disponible',
    'WNXM': 'No disponible',
    'UMA': 'UMA',
    'SNX': 'SNX',
    'GLMR': 'No disponible',
    'ZRX': 'ZRX',
    'ALICE': 'No disponible',
    'SFP': 'No disponible',
    'MDX': 'No disponible',
    'YFII': 'No disponible',
    'YGG': 'No disponible',
    'CTSI': 'No disponible',
    'INJ': 'No disponible',
    'BLZ': 'No disponible',
    'GTC': 'No disponible',
    'ERN': 'No disponible',
    'FLM': 'No disponible',
    'UOS': 'No disponible',
    'FLUX': 'No disponible',
    'LOOM': 'LOOM',
    'SOLVE': 'No disponible',
    'RAY': 'No disponible',
    'SAND': 'SAND',
    'DODO': 'No disponible',
    'AVA': 'No disponible',
    'SLP': 'No disponible',
    'IRIS': 'No disponible',
    'CTK': 'No disponible',
    'DNT': 'DNT',
    'IDEX': 'No disponible',
    'TVK': 'No disponible',
    'POWR': 'POWR',
    'BTS': 'No disponible',
    'AXS': 'AXS',
    'BTG': 'No disponible',
    'GRS': 'No disponible',
    'LRC': 'LRC',
    'FUN': 'No disponible',
    'DGB': 'DGB',
    'BCD': 'No disponible',
    'REP': 'REP',
    'MFT': 'No disponible',
    'STORJ': 'STORJ',
    'ZEN': 'ZEN',
    'QSP': 'No disponible',
    'ANT': 'ANT',
    'CVC': 'CVC',
    'MDA': 'No disponible',
    'PPT': 'No disponible',
    'MANA': 'MANA',
    'BAT': 'BAT',
    'ZRX': 'ZRX',
    'LINK': 'LINK',
    'ETH': 'ETH',
    'LTC': 'LTC',
    'ETC': 'ETC',
    'DAI': 'DAI',
    'USDC': 'USDC',
    'USDT': 'USDT',
    'XLM': 'XLM',
    'XRP': 'XRP',
    'ADA': 'ADA',
    'EOS': 'EOS',
    'XTZ': 'XTZ',
    'DASH': 'DASH',
    'ZEC': 'ZEC',
    'KNC': 'KNC',
    'ATOM': 'ATOM',
    'ALG': 'ALGO',
    'COMP': 'COMP',
    'DOT': 'DOT',
    'KSM': 'KSM',
    'OMG': 'OMG',
    'PAXG': 'PAXG',
    'REP': 'REP',
    'SC': 'SC',
    'WAVES': 'WAVES',
    'ICX': 'ICX',
    'GNO': 'GNO',
    'LSK': 'LSK',
    'NANO': 'NANO',
    'KAVA': 'KAVA',
    'YFI': 'YFI',
    'FIL': 'FIL',
    'TRX': 'TRX',
    'FLOW': 'FLOW',
    'SNX': 'SNX',
    'SUSHI': 'SUSHI',
    'AAVE': 'AAVE',
    'UNI': 'UNI',
    'MKR': 'MKR',
    'GRT': 'GRT',
    'BAL': 'BAL',
    'CRV': 'CRV',
    '1INCH': '1INCH',
    'REN': 'REN',
    'OCEAN': 'OCEAN',
    'BAT': 'BAT',
    'ENJ': 'ENJ',
    'CHZ': 'CHZ',
    'ADA': 'ADA',
    'SOL': 'SOL',
    'DOGE': 'DOGE',
    'SHIB': 'SHIB',
    'FTM': 'FTM',
    'AVAX': 'AVAX',
    'NEAR': 'NEAR',
    'QNT': 'QNT',
    'ICP': 'ICP',
    'APE': 'APE',
    'EGLD': 'EGLD',
    'MANA': 'MANA',
    'SAND': 'SAND',
    'AXS': 'AXS',
    'GMT': 'GMT',
    'CRO': 'CRO',
    'FTM': 'FTM',
    'NEO': 'NEO',
    'KSM': 'KSM',
    'CHZ': 'CHZ',
    'FLOW': 'FLOW',
    'GRT': 'GRT',
    'LRC': 'LRC',
    'STX': 'STX',
    'BAT': 'BAT',
    'ZRX': 'ZRX',
    'OMG': 'OMG',
    'ENJ': 'ENJ',
    'OXT': 'OXT',
    'PAXG': 'PAXG',
    'REN': 'REN',
    'KNC': 'KNC',
    'BAL': 'BAL',
    'COMP': 'COMP',
    'CRV': 'CRV',
    'SNX': 'SNX',
    'YFI': 'YFI',
    'SUSHI': 'SUSHI',
    'MKR': 'MKR',
    'UMA': 'UMA',
    'DASH': 'DASH',
    'SC': 'SC',
    'REP': 'REP',
    'ICX': 'ICX',
    'NANO': 'NANO',
    'WAVES': 'WAVES',
    'GNO': 'GNO',
    'ANT': 'ANT',
    'MLN': 'MLN',
    'BNT': 'BNT',
    'QTUM': 'QTUM',
    'DGB': 'DGB',
    'STORJ': 'STORJ',
    'NMR': 'NMR',
    'MANA': 'MANA',
    'DNT': 'DNT',
    'REPV2': 'REP',
    'POWR': 'POWR',
    'KAR': 'No disponible',
    'MOVR': 'No disponible',
    'RMRK': 'No disponible',
    'PHA': 'No disponible',
    'BOND': 'No disponible',
    'CFG': 'No disponible',
    'AIR': 'No disponible',
    'HUM': 'No disponible',
    'KILT': 'No disponible',
    'LKSM': 'No disponible',
    'CSM': 'No disponible',
    'TEER': 'No disponible',
    'XOR': 'No disponible',
    'XRT': 'No disponible',
    'PKEX': 'No disponible',
    'VRA': 'No disponible',
    'AKRO': 'No disponible',
    'UTK': 'No disponible',
    'XCAD': 'No disponible',
    'AZERO': 'No disponible',
    'PDEX': 'No disponible',
    'IDEX': 'No disponible',
    'CQT': 'No disponible',
    'ORION': 'No disponible',
    'PCX': 'No disponible',
    'ACA': 'No disponible',
    'AUSD': 'No disponible',
    'ASTR': 'No disponible',
    'GLMR': 'No disponible',
    'TAI': 'No disponible',
    'CFG': 'No disponible',
}

# ohlc_mapping.py

ohlc_mapping = {
    'XBTUSD': 'XXBTZUSD',
    'XBTUSDT': 'XXBTZUSDT',
    'XBTUSDC': 'XXBTZUSDC',
    'XBTJPY': 'XXBTZJPY',
    'XBTEUR': 'XXBTZEUR',
    'ETHUSD': 'XETHZUSD',
    'ETHUSDT': 'XETHZUSDT',
    'ETHUSDC': 'XETHZUSDC',
    'ETHEUR': 'XETHZEUR',
    'ETHJPY': 'XETHZJPY',
    'XRPUSD': 'XXRPZUSD',
    'XRPEUR': 'XXRPZEUR',
    'LTCUSD': 'XLTCZUSD',
    'LTCEUR': 'XLTCZEUR',
    'BCHUSD': 'BCHUSD',
    'BCHEUR': 'BCHEUR',
    'DOTUSD': 'DOTUSD',
    'DOTEUR': 'DOTEUR',
    'ADAUSD': 'ADAUSD',
    'ADAEUR': 'ADAEUR',
    'SOLUSD': 'SOLUSD',
    'SOLEUR': 'SOLEUR',
    'LINKUSD': 'LINKUSD',
    'LINKEUR': 'LINKEUR',
    'XLMUSD': 'XXLMZUSD',
    'XLMEUR': 'XXLMZEUR',
    'XMRUSD': 'XXMRZUSD',
    'XMREUR': 'XXMRZEUR',
    'EOSUSD': 'EOSUSD',
    'EOSEUR': 'EOSEUR',
    'TRXUSD': 'TRXUSD',
    'TRXEUR': 'TRXEUR',
    'DASHUSD': 'DASHUSD',
    'DASHEUR': 'DASHEUR',
    'ETCUSD': 'XETCZUSD',
    'ETCEUR': 'XETCZEUR',
    'ZECUSD': 'XZECZUSD',
    'ZECEUR': 'XZECZEUR',
    'FILUSD': 'FILUSD',
    'FILEUR': 'FILEUR',
    'USDTUSD': 'USDTZUSD',
    'USDTEUR': 'USDTEUR',
    'USDCUSD': 'USDCUSD',
    'USDCEUR': 'USDCEUR',
    'ALGOUSD': 'ALGOUSD',
    'ALGOEUR': 'ALGOEUR',
    'ATOMUSD': 'ATOMUSD',
    'ATOMEUR': 'ATOMEUR',
    'GRTUSD': 'GRTUSD',
    'GRTEUR': 'GRTEUR',
    'MATICUSD': 'MATICUSD',
    'MATICEUR': 'MATICEUR',
    'AAVEUSD': 'AAVEUSD',
    'AAVEEUR': 'AAVEEUR',
    'UNIUSD': 'UNIUSD',
    'UNIEUR': 'UNIEUR',
    'XTZUSD': 'XXTZUSD',
    'XTZEUR': 'XXTZZEUR',
    'COMPUSD': 'COMPUSD',
    'COMPEUR': 'COMPEUR',
    'YFIUSD': 'YFIUSD',
    'YFIEUR': 'YFIEUR',
    'SNXUSD': 'SNXUSD',
    'SNXEUR': 'SNXEUR',
    'SUSHIUSD': 'SUSHIUSD',
    'SUSHIEUR': 'SUSHIEUR',
    'DOGEUSD': 'XXDGZUSD',
    'DOGEEUR': 'XXDGZEUR',
    'MANAUSD': 'MANAUSD',
    'MANAEUR': 'MANAEUR',
    'ENJUSD': 'ENJUSD',
    'ENJEUR': 'ENJEUR',
    'BATUSD': 'BATUSD',
    'BATEUR': 'BATEUR',
    'SCUSD': 'SCUSD',
    'SCEUR': 'SCEUR',
    'DGBUSD': 'DGBUSD',
    'DGBEUR': 'DGBEUR',
    'NANOUSD': 'NANOUSD',
    'NANOEUR': 'NANOEUR',
    'WAVESUSD': 'WAVESUSD',
    'WAVESEUR': 'WAVESEUR',
    'ICXUSD': 'ICXUSD',
    'ICXEUR': 'ICXEUR',
    'QTUMUSD': 'QTUMUSD',
    'QTUMEUR': 'QTUMEUR',
    'OMGUSD': 'OMGUSD',
    'OMGEUR': 'OMGEUR',
    'ZRXUSD': 'ZRXUSD',
    'ZRXEUR': 'ZRXEUR',
    'KAVAUSD': 'KAVAUSD',
    'KAVAEUR': 'KAVAEUR',
    'STORJUSD': 'STORJUSD',
    'STORJEUR': 'STORJEUR',
    'OXTUSD': 'OXTUSD',
    'OXTEUR': 'OXTEUR',
    'KSMUSD': 'KSMUSD',
    'KSMEUR': 'KSMEUR',
    'DAIUSD': 'DAIUSD',
    'DAIEUR': 'DAIEUR',
    'EURUSD': 'ZEURZUSD',
}

mapped_ohlc_reverse = {
    'XBTUSD': 'BTC/USD',
    'XBTUSDT': 'BTC/USDT',
    'XBTUSDC': 'BTC/USDC',
    'XBTJPY': 'BTC/JPY',
    'XBTEUR': 'BTC/EUR',
    'ETHUSD': 'ETH/USD',
    'ETHUSDT': 'ETH/USDT',
    'ETHUSDC': 'ETH/USDC',
    'ETHEUR': 'ETH/EUR',
    'ETHJPY': 'ETH/JPY',
    'XRPUSD': 'XRP/USD',
    'XRPEUR': 'XRP/EUR',
    'LTCUSD': 'LTC/USD',
    'LTCEUR': 'LTC/EUR',
    'BCHUSD': 'BCH/USD',
    'BCHEUR': 'BCH/EUR',
    'DOTUSD': 'DOT/USD',
    'DOTEUR': 'DOT/EUR',
    'ADAUSD': 'ADA/USD',
    'ADAEUR': 'ADA/EUR',
    'SOLUSD': 'SOL/USD',
    'SOLEUR': 'SOL/EUR',
    'LINKUSD': 'LINK/USD',
    'LINKEUR': 'LINK/EUR',
    'XLMUSD': 'XLM/USD',
    'XLMEUR': 'XLM/EUR',
    'XMRUSD': 'XMR/USD',
    'XMREUR': 'XMR/EUR',
    'EOSUSD': 'EOS/USD',
    'EOSEUR': 'EOS/EUR',
    'TRXUSD': 'TRX/USD',
    'TRXEUR': 'TRX/EUR',
    'DASHUSD': 'DASH/USD',
    'DASHEUR': 'DASH/EUR',
    'ETCUSD': 'ETC/USD',
    'ETCEUR': 'ETC/EUR',
    'ZECUSD': 'ZEC/USD',
    'ZECEUR': 'ZEC/EUR',
    'FILUSD': 'FIL/USD',
    'FILEUR': 'FIL/EUR',
    'USDTUSD': 'USDT/USD',
    'USDTEUR': 'USDT/EUR',
    'USDCUSD': 'USDC/USD',
    'USDCEUR': 'USDC/EUR',
    'ALGOUSD': 'ALGO/USD',
    'ALGOEUR': 'ALGO/EUR',
    'ATOMUSD': 'ATOM/USD',
    'ATOMEUR': 'ATOM/EUR',
    'GRTUSD': 'GRT/USD',
    'GRTEUR': 'GRT/EUR',
    'MATICUSD': 'MATIC/USD',
    'MATICEUR': 'MATIC/EUR',
    'AAVEUSD': 'AAVE/USD',
    'AAVEEUR': 'AAVE/EUR',
    'UNIUSD': 'UNI/USD',
    'UNIEUR': 'UNI/EUR',
    'XTZUSD': 'XTZ/USD',
    'XTZEUR': 'XTZ/EUR',
    'COMPUSD': 'COMP/USD',
    'COMPEUR': 'COMP/EUR',
    'YFIUSD': 'YFI/USD',
    'YFIEUR': 'YFI/EUR',
    'SNXUSD': 'SNX/USD',
    'SNXEUR': 'SNX/EUR',
    'SUSHIUSD': 'SUSHI/USD',
    'SUSHIEUR': 'SUSHI/EUR',
    'DOGEUSD': 'DOGE/USD',
    'DOGEEUR': 'DOGE/EUR',
    'MANAUSD': 'MANA/USD',
    'MANAEUR': 'MANA/EUR',
    'ENJUSD': 'ENJ/USD',
    'ENJEUR': 'ENJ/EUR',
    'BATUSD': 'BAT/USD',
    'BATEUR': 'BAT/EUR',
    'SCUSD': 'SC/USD',
    'SCEUR': 'SC/EUR',
    'DGBUSD': 'DGB/USD',
    'DGBEUR': 'DGB/EUR',
    'NANOUSD': 'NANO/USD',
    'NANOEUR': 'NANO/EUR',
    'WAVESUSD': 'WAVES/USD',
    'WAVESEUR': 'WAVES/EUR',
    'ICXUSD': 'ICX/USD',
    'ICXEUR': 'ICX/EUR',
    'QTUMUSD': 'QTUM/USD',
    'QTUMEUR': 'QTUM/EUR',
    'OMGUSD': 'OMG/USD',
    'OMGEUR': 'OMG/EUR',
    'ZRXUSD': 'ZRX/USD',
    'ZRXEUR': 'ZRX/EUR',
    'KAVAUSD': 'KAVA/USD',
    'KAVAEUR': 'KAVA/EUR',
    'STORJUSD': 'STORJ/USD',
    'STORJEUR': 'STORJ/EUR',
    'OXTUSD': 'OXT/USD',
    'OXTEUR': 'OXT/EUR',
    'KSMUSD': 'KSM/USD',
    'KSMEUR': 'KSM/EUR',
    'DAIUSD': 'DAI/USD',
    'DAIEUR': 'DAI/EUR',
    'EURUSD': 'EUR/USD',
}
